### ISSUE TITLE
Library do not work after upgrade to Angular 6

### ISSUE THREAD

**Issue by karolke** [shepherdwind/velocity.js#102]
After upgrade from Angular 5, to Angular 6.0.7, cannot compile (using "ng serve"), and got error:

> ERROR in ./node_modules/velocityjs/src/parse/index.js
Module not found: Error: Can't resolve 'path' in 'XXX\node_modules\velocityjs\src\parse'

After playing with source code, it seems, that problem is undefined 'path' variable at velocityjs/src/parse/index.js

I did not change velocityjs import command, and previously working one was: 
"let Velocity = require('velocityjs');" or "import * as Velocity from 'velocityjs';

**Comment by shepherdwind** [comment]
What build tool did you used? webpack or something else?

I try this lib with webpack4, It is work fine.

**Comment by shepherdwind** [comment]
https://github.com/shepherdwind/velocity.js/blob/fa72a31daf2e28f52b44a0e5e30c2986e1df19ef/package.json#L21-L24

This config will make the build tool ignore fs and path dependency, Maybe your tool do not support this feature.

**Comment by karolke** [comment]
I use "webpack": "^4.10.2" for build tool. 

With config you've provided, everything works perfect, thanks! Will you apply this fix to main relase?

**Comment by shepherdwind** [comment]
1.0.2 published . I forget to push this change to npm .
