### ISSUE TITLE
Support promises from context functions

### ISSUE THREAD

**Issue by marcusds** [shepherdwind/velocity.js#117]
It would be great if we could use handle promises, as it is now I don't see a way to use any type of function that uses promises in a context function or a macro.

**Comment by shepherdwind** [comment]
I don't know very clear what is you mean about support promise. You can use function in context, promise also is ok. But the render function is synchronized, so do you want render asynchronous ? 

Maybe write an example will be helpful. I will close this issue, if you want more help, you can reopen it.

**Comment by marcusds** [comment]
If in a Velocity template when calling a method like let's say $vue.prerender(), if that method is attached to a asynchronous Javascript, like let's say https://www.npmjs.com/package/prerender-spa-plugin, that returns a promise and works async it doesn't work with this library.

**Comment by cyberwombat** [comment]
@shepherdwind  can you give an example? I too cannot use promises. You say "Support promises from context functions" but how?
```
const context = {
      data: {},
      utils: { toUpper: async f => Promise.resolve(`${f.toUpperCase()}`) } // also tried toUpper: f => Promise.resolve(`${f.toUpperCase()}`)
    }
    const tpl = 'Hello my name is $utils.toUpper("yoda")'
    const res = renderTemplate(tpl, context)
    expect(res).toBe('Hello my name is YODA') // I get "Hello my name is [object Promise]"
```
