### ISSUE TITLE
String pipe symbol not implemented

### ISSUE THREAD

**Issue by cyberwombat** [shepherdwind/velocity.js#126]
Aoache VTL has option for default value:

`$ [ { ] identifier . identifier ( [ parameter list... ] ) [ [ | alternate value ] } ]`

Ex: `: ${person.name|'John Doe'}`

But I get an error when I try this in velocityjs:

`console.log(require('velocityjs').render("${ctx.test|'sd'}", { test: 'foo' }))`

**Comment by shepherdwind** [comment]
This feature will be a big change, the repo will not provide more feature now.
