### ISSUE TITLE
Support the $util.qr directive

### ISSUE THREAD

**Issue by jeff-shep** [shepherdwind/velocity.js#127]
Great library! Really improving our unit testing of AWS AppSync Resolver Mapping Templates that are written in Velocity Template Language. Would be great to support the $util.qr. Open to working on this as well but just noting the Issue for now.

Links to the AppSync directive is here: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html

**Comment by shepherdwind** [comment]
You should extends util your self
