### ISSUE TITLE
String matches does not work

### ISSUE THREAD

**Issue by jprivillaso** [shepherdwind/velocity.js#138]
Hello! 

I am trying to compile the following expression, and somehow it does work. 

```
#set($limit = "4")
#if( $limit != '' && $limit.matches('^\d+$'))
  { "response": 1 }
#else
  { "response": 2 }
#end
```

Isn't it supposed to work? I need to validate if a string contains a number.

**Current Response**
```
{ "response": 2 }
```

**Expected Response**
```
{ "response": 1 }
```

Thank you

**Comment by shepherdwind** [comment]
That because the String do not have the matches method, this engine run on javascript , so you can just use javascript string method, for example  https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/match

```
#if( $limit != '' && $limit.match('^\\d+$'))
  { "response": 1 }
#else
  { "response": 2 }
#end
```

**Comment by jprivillaso** [comment]
That totally makes sense. I used a regex to replace `matches` with `match` and escape the parameter appropriately.
Thank you so much @shepherdwind
