### ISSUE TITLE
Support method with arguments

### ISSUE THREAD

**Issue by henryli-okta** [shepherdwind/velocity.js#144]
In the test code, I didn't find a case for a method with parameters like $foo($var1). Would like this engine to support this feature.

other cases:
`$!{f.foo($!bar)}`

**Comment by shepherdwind** [comment]
here is the example 
https://github.com/shepherdwind/velocity.js/blob/109eecd5e2ebf846815dc8a46ba043d785153fde/test/references.test.js#L10-L15

there is no different between variable and literal when you use parameters

**Comment by henryli-okta** [comment]
Nice! It works. Can we add the following or similar as an example?
```
var vmCode = "#set( $num = 2 )\n$f.plusOne($num)";
var context = {f: {plusOne: new Function("num", "return num");}};
assert.strictEqual(render(vmCode, context), 2);
```
