### ISSUE TITLE
Parse String to Int

### ISSUE THREAD

**Issue by ottokruse** [shepherdwind/velocity.js#145]
First of all, great library, thank you for building it.

This VTL is not supported:

```
#set($mystring="123")
#set($Integer=1)
#set($myint=$Integer.parseInt($mystring))
```

(after some googling found this is a way to parse a String to an Int)

However was able to make it work, by doing this, before running the test:

```js
Number.prototype.parseInt = parseInt
```

Do you maybe have a better recommendation?

**Comment by shepherdwind** [comment]
2.0.6 published.  see example

https://github.com/shepherdwind/velocity.js/blob/91baab1cbd3979f1cc4f1ad850433541fdf6566d/test/references.test.js#L222-L248

**Comment by ottokruse** [comment]
Awesome! Thanks for the quick turn around 🎉
