### ISSUE TITLE
除法、比较运算，VM、js结果不一致bug

### ISSUE THREAD

**Issue by 518yxx** [shepherdwind/velocity.js#41]
1. 整数除法问题：java中整数除法结果会取整，这与js语法不一致；
2. 比较运算问题：VM中对象==运算会用对象的value值进行比较运算，与js语法不一致；

**Comment by shepherdwind** [comment]
这种运算的问题，很难抹平的，我也只能按照js的运算方式来实现了，如果你觉得有必要完全按照java的风格的话，只能自己把[Velocity.Compile.prototype.getExpression](https://github.com/shepherdwind/velocity.js/blob/master/src/compile/expression.js#L11)方法覆盖为你自己的实现就行。
