### ISSUE TITLE
#stop支持

### ISSUE THREAD

**Issue by lemoncolaz** [shepherdwind/velocity.js#48]
#stop计划支持吗？看了沉鱼的代码，好像支持。如果没有计划加进去，我先参考沉鱼的版本修改一下。

**Comment by shepherdwind** [comment]
我看下，应该可以支持。

**Comment by shepherdwind** [comment]
发布了0.7.0-beta1, 你看可以试下

```
$ npm install velocityjs@beta
```

另外，看下我的[用例](https://github.com/shepherdwind/velocity.js/pull/49/files#diff-a484ee2e9bab1a171520a083fcaecd22)是否够用了。

**Comment by lemoncolaz** [comment]
恩，我看一下

**Comment by lemoncolaz** [comment]
好像不行啊，没看到parse/index.js里的rules里增加匹配#stop的正则表达式，也没看到处理stop的方法

**Comment by shepherdwind** [comment]
不需要改parse，

```
      this.directive = {
        stop: function() {
         self._state.stop = true;
          return '';
        }
      };
```

还有这一样：https://github.com/shepherdwind/velocity.js/pull/49/files#diff-a509cb5a1016a02a707bb7b706e93c5cR199

测试用例可以pass，肯定那几个例子是ok的

**Comment by shepherdwind** [comment]
真实改的就几行compile/compile.js的两个方法，init增加this.directive对象，在_render方法里面增加退出功能。

其他都是样式调整。

**Comment by lemoncolaz** [comment]
#stop() 现在可用，我不太懂velocity，看到rd写的代码里是写的#stop
