### ISSUE TITLE
$!a.b， 若a不存在，会报错

### ISSUE THREAD

**Issue by yangxuanxing** [shepherdwind/velocity.js#54]
$!a.b， 若a不存在，线上解析没问题，mock会js报错

推荐修改src/compile/references.js

    utils.some(ast.path, function(property){
      //第三个参数，返回后面的参数ast
      ret = ret && this.getAttributes(property, ret, ast);
    }, this);

**Comment by shepherdwind** [comment]
mock会js报错是什么意思啊？

**Comment by shepherdwind** [comment]
执行js是啥？贴一个运行的代码来看看。

**Comment by yangxuanxing** [comment]
不好意思，前两天没注意邮件，上面描述的有点问题，报错代码如下：

    var Velocity = require('velocityjs');
    Velocity.render('this thows error: $!a.b.c', {a: {b: null}});

**Comment by shepherdwind** [comment]
0.7.3

上周请假了，今天刚回来。
