### ISSUE TITLE
解析引擎怎么结合express呢？

### ISSUE THREAD

**Issue by YanYITian** [shepherdwind/velocity.js#59]
我的代码是这样的
![image](https://cloud.githubusercontent.com/assets/5938107/11989926/43794652-aa41-11e5-9cd1-77797603ddbb.png)

但是报错了

![image](https://cloud.githubusercontent.com/assets/5938107/11989930/618ab50e-aa41-11e5-921c-54dbf54173bf.png)

**Comment by shepherdwind** [comment]
http://xml.iteye.com/blog/1964213

**Comment by shepherdwind** [comment]
你看下这个怎么样？
