### ISSUE TITLE
期望支持`#[[don't parse me!]]#`语法

### ISSUE THREAD

**Issue by holyzfy** [shepherdwind/velocity.js#60]
当在页面里使用jQuery的$符时， 有时候会因为$符被解析而导致出错parseError，希望能支持`#[[don't parse me!]]#`语法

语法参见：http://velocity.apache.org/engine/devel/user-guide.html

**Comment by shepherdwind** [comment]
应该是有支持的吧

https://github.com/shepherdwind/velocity.js/blob/master/tests/compile.js#L323

**Comment by shepherdwind** [comment]
可以把你出错的场景贴出来看下

**Comment by holyzfy** [comment]
sorry是我的问题，在处理#parse时多次调用`Velocity.render`时出现的这个情况，已解决。

感谢！

**Comment by shepherdwind** [comment]
#parse 的实现可以参考 https://github.com/shepherdwind/velocity.js/blob/master/tests/compile.js#L644 的。
