### ISSUE TITLE
Unicode escaping: why ? how to config ?

### ISSUE THREAD

**Issue by dherault** [shepherdwind/velocity.js#62]
Hi, thanks for this awesome module, it works a charm!

in `src/compile/index.js` you have:
```javascript
function Velocity(asts, config) {
  this.asts = asts;
  this.config = {
    // 自动输出为经过html encode输出
    escape: true,
    // 不需要转义的白名单
    unescape: {}
  };
  utils.mixin(this.config, config);
  this._state = { stop: false, break: false };
  this.init();
}
```
I would like to set `escape` to `false`. Escaping those: `<, >, &` with `&lt;, &gt;, &amp;` is not a behavior I want in my application.

For now I'm using a fork of your module with `escape` set to `false`, but I would love to use your code if this could be configured!

What do you think ? If you're busy, I can PR a configurable something.
Thanks!

PS : Why escaping in the first place ?
PPS : your MIT license is outdated (2012-2013) :wink:

**Comment by shepherdwind** [comment]
You can find some from doc. https://github.com/shepherdwind/velocity.js#config

Or, there are some example in test case: https://github.com/shepherdwind/velocity.js/blob/master/tests/compile.js#L144


Why escape in the first place? That long story, For first time, this lib is write for mock java version velocity template. That java version have this logic, escape default.

**Comment by dherault** [comment]
Wow I'm sorry I bothered you for something that was in the README :sob: 
Thanks for the quick answer and explanation!
