### ISSUE TITLE
#parse使用求教

### ISSUE THREAD

**Issue by xingzhewj** [shepherdwind/velocity.js#68]
关于模板中的#parse 宏，看文档和issue还是不知道在node中究竟怎样实际使用！
例如在a.vm文件中有一行：#parse("./b.vm");
b.vm是个vm模板文件，里面有#set宏！
求教如何写才能正确渲染出来a.vm的内容？

**Comment by shepherdwind** [comment]
https://github.com/shepherdwind/velocity.js/blob/master/tests/compile.js#L532 看这个用例

**Comment by xingzhewj** [comment]
非常感谢！！！ 已解决！
