### ISSUE TITLE
macors支持

### ISSUE THREAD

**Issue by xingzhewj** [shepherdwind/velocity.js#69]
对于#macro (test) 这种的在vm中调用的时候，现在貌似只能采用#test()这种调用方式。
可否也支持#test这种方式的调用呢？

**Comment by shepherdwind** [comment]
不是很明白什么意思？可以解释更清楚一些吗？

**Comment by xingzhewj** [comment]
是这样子的。例如a.vm中有#macro (test)一行，在b.vm中#test调用的时候没有调用成功而是原样输出了#test, 如果我在b.vm中#test()这样去调用就没有问题了，就是想可以也支持#test这种的调用吗？

**Comment by shepherdwind** [comment]
http://velocity.apache.org/engine/devel/user-guide.html#velocimacros velocity 没有你说的这种 `#test` 直接执行的吧。

**Comment by xingzhewj** [comment]
是这样的。tomcat中的velocity配置确实也识别那样的写法，但由于vm不好轻易改动，所以看是否也能支持这样的写法！

**Comment by shepherdwind** [comment]
我看下怎么处理下

**Comment by xingzhewj** [comment]
还想请教一个问题！如果我配置的模板数据是{a:'asd', b:3}，vm模板中  var a = ${a};    渲染完后变成了var a = asd;  如果我想输出为字符串的话是不是得在模板数据中就要改成'"asd"'这样的值还是说咱们有什么配置可以处理呢？

**Comment by xingzhewj** [comment]
ERROR Parse error on line 67: #foreach(${itemData} in ${defaultData})  Expecting 'ID', got 'MAP_BEGIN'
查到正常写法是#foreach($itemData in $defaultData)；但是可否支持上面的写法呢？

**Comment by shepherdwind** [comment]
0.8.4 修复了 #foreach 的问题

**Comment by shepherdwind** [comment]
那种没有括号的，估计比较难实现了，而且容易和 css 选择器冲突啥的。

**Comment by xingzhewj** [comment]
恩恩！我修改下vm，按照标准得来！非常给力！！点赞！！！
