### ISSUE TITLE
Add support for #{end}

### ISSUE THREAD

**Issue by tomerla** [shepherdwind/velocity.js#72]
Hi,
Currently the library only support the **#end** directive
e.g: ```#if($foo)<div>conditional text</div>#end```

Please add support for the **#{end}** directive (which is supported by the official *apache velocity*)
e.g: ```#if($foo)<div>conditional text</div>#{end}```

Thanks!

**Comment by shepherdwind** [comment]
0.9.0

**Comment by tomerla** [comment]
wow - thx man!
working like a charm :)
