### ISSUE TITLE
java的神器。不解释。

### ISSUE THREAD

**Issue by githublaohu** [shepherdwind/velocity.js#74]
但是文档好少。
列子好少。

**Comment by shepherdwind** [comment]
要什么例子，可以看看用例 https://github.com/shepherdwind/velocity.js/blob/master/tests/compile.js

**Comment by githublaohu** [comment]
使用思路，两个列子，区别大好。
解析之后，不自动，替换 节点里面的HTML吗？

**Comment by shepherdwind** [comment]
你那个需要的是 vue 那种 mvvm 库了，这个只是解析 velocity 模板的解析器。

**Comment by githublaohu** [comment]
java使用 velocity 作为模板的项目很多，不方便前端开发。
有了 velocity.js 真是前段神器。
如果能提供自动 解析之后，自动呼唤那就好了。
这个功能，我可帮维护。
还是感觉有点乱。

**Comment by shepherdwind** [comment]
这个要做的话也是可以的，但会有点复杂，一个思路是这样的

- 第一步，把 velocity 转换为 vue 模板
- 调用 vue 渲染

直接实现一个 mvvm 复杂度太高，转换一次成本会低很多。简单的变量替换什么的应该没问题

**Comment by githublaohu** [comment]
不要那么复杂，不要mvvm。
只需要哪里获取，就还原哪里。
不要vue，不要依赖。

**Comment by shepherdwind** [comment]
那你自己实现就好了，每次都 innerHTML 重新渲染一下
