### ISSUE TITLE
Option to strip unresolved variables?

### ISSUE THREAD

**Issue by misto** [shepherdwind/velocity.js#75]
Hi,

Thank you very much for this great library. Is there an option to simply strip all $variables that can't be found in the context? I'm using the library to show a preview text when the user is filling out a form, so I'd like to hide the $variables if the form is empty.

**Comment by shepherdwind** [comment]
https://github.com/shepherdwind/velocity.js/blob/master/index.d.ts#L11 the last param silence can hide all $variables when var is empy. Or you can write code like this `$!variables`

**Comment by shepherdwind** [comment]
there is an example https://github.com/shepherdwind/velocity.js/blob/master/tests/compile.js#L91

**Comment by misto** [comment]
Oh, perfect. Thank you.
