### ISSUE TITLE
如何解析为html？

### ISSUE THREAD

**Issue by travelling-wxy** [shepherdwind/velocity.js#80]
比如 $article.content 是一个html片段，但是输出到网页上就成以 string 展示了，如何解析成 html 展示呢?

**Comment by shepherdwind** [comment]
是因为有转义的吧，你怎么使用的，默认是开启转义了，你可以关闭，或者配置不转义 https://github.com/shepherdwind/velocity.js/blob/master/index.d.ts#L3

**Comment by travelling-wxy** [comment]
多谢，已解决。
