### ISSUE TITLE
trim() function doesn't work 

### ISSUE THREAD

**Issue by oariamit** [shepherdwind/velocity.js#86]
Hi,

First of all I would like to thank you for creating this wonderful library.  I am using this library to create a template preview for electronic shelf labels. However, when trim() method is used the velocity engine is unable to compile it.  Please check the following sample code where it fails -

#set($varStartDate = "")
#if(${StartDate} != ""  && ${StartDate} != " " )
	#set($varStartDateTemp = ${StartDate})
	#set($varStartDate = "$varStartDateTemp.trim()")
#end

I get this error in console - Cannot create property '$sys' on string

**Comment by shepherdwind** [comment]
I write an simple test 

```js
    it('#86', function() {
      var vm = '#set($varStartDate = "") #if(${StartDate} != "" && ${StartDate} != " " ) #set($varStartDateTemp = ${StartDate}) #set($varStartDate = "$varStartDateTemp.trim()") #end hello world ${varStartDate}';
      console.log(render(vm, { StartDate: '12' }));
    });
```

The result is '12' , which should be no problem. 

Can you give me you a demo code ? So that I can run it on my computer.

**Comment by oariamit** [comment]
We were able to reproduce this issue on your website to try velocity http://git.shepherdwind.com/velocity.js/try/index.html

Please try this video link
http://www.fastswf.com/Iwc42nc

Thanks for all your efforts
Regards,
amitabha

**Comment by shepherdwind** [comment]
You can submit you velocity template code to this issue. That website maintenance now.

**Comment by oariamit** [comment]
Hello,

Sorry for the delayed response. I downloaded the latest velocity.js from github and I could run the test cases successfully. So, it seems I was wrong about the velocity code not supporting substring () and trim() methods. However, when I try to use the broswer.html example (examples/browser.html) to load Velocity it still loads the old "velocityjs/0.4.6/index". When I try to change it the program doesn't work. 

I would really be grateful, if you can provide an example of how to load all the dependencies for the latest velocity. I want to run the velocity code on a browser.

Thanks for your help in advance.

Regards,
amitabha singha

**Comment by oariamit** [comment]
Hi Again,

I have used browserify to solve this issue. Thanks for your good work. I am closing this issue from my side as trim is working

Regards,
amitabha singha
