### ISSUE TITLE
error message are not seen

### ISSUE THREAD

**Issue by abhsinh2** [shepherdwind/velocity.js#89]
I use below code:

try {
        Velocity.parse(content);
 } catch (err) {
        console.log("Parsing Error:" + JSON.stringify(err));
 }

with content:

if($name)
#end

then console.log prints only {}

**Comment by shepherdwind** [comment]
Please give me you that content which you passed to Velocity.parse . So I can try this error condition on my compute.

**Comment by abhsinh2** [comment]
Try below:

if($name)
#end

**Comment by abhsinh2** [comment]
Also, it would be good if we can tell line number in error message so that editor can show errors on UI

**Comment by shepherdwind** [comment]
I try render this input on java version, which will not throw too.
