### ISSUE TITLE
Not getting syntax error for given templates

### ISSUE THREAD

**Issue by abhsinh2** [shepherdwind/velocity.js#93]
I am not getting syntax error for below templates:

#if( $foo > 10 )
ddd
**#els**
#end

**#foreach()**
interface $ifName
descriprion $desc
#end

#if($message != ""**))**
interface $int
description $desc
#end

**Comment by shepherdwind** [comment]
I have try this in java version, which will not throw error. So, I think this should not be a problem.

a.vm

```
#set($foo = 11)
#if( $foo > 10 )
ddd
#els
#end
```

parse result

```
$ java -jar target/velocity-checker-1.0.0.jar a.vm
```
