### ISSUE TITLE
Is support #@bodytext()?

### ISSUE THREAD

**Issue by HejieShao** [shepherdwind/velocity.js#96]
#macro(bodytext)
<!DOCTYPE html>
	<head>
    <meta charset="utf-8">
    </head>
	<body>
		$!bodyContent
	</body>
</html>
#end

#@bodytext()

I try this way, but velocity.js is not support #@? How can I use #@bodytext()?

**Comment by shepherdwind** [comment]
Ok, I will add this feature right now.

**Comment by shepherdwind** [comment]
1.0.0 published
