### ISSUE TITLE
请问怎样支持  #set($layout="layout.vm") 这种模板写法

### ISSUE THREAD

**Issue by julabs** [shepherdwind/velocity.js#98]
试了下，只支持 `#parse` 引入，但不支持 `#set($layout="layout.vm") ` 。
`#set($layout="layout.vm")` 的写法只是将字符 `layout.vm` 赋值给变量`$layout`。

谢谢

**Comment by shepherdwind** [comment]
java 有这种写法么？

**Comment by julabs** [comment]
有的，是和 **Spring** 一起使用的，可以搜索下 `velocity layout`。
[Velocity布局（layout）功能介绍](http://qstar.iteye.com/blog/1677130)

**Comment by shepherdwind** [comment]
这种事需要自己来实现了。基本思路是这样的

1. 第一步，渲染内容页面
2. 第二步，从渲染结果中拿到 layout 变量
3. 第三步，基于 layout 变量渲染 layout 对应的页面，上一个渲染的内容作为 screen_content 变量

**Comment by shepherdwind** [comment]
spring 也是封装了 velocity 包来实现的，这个特性不是模板的特性了。

**Comment by julabs** [comment]
哦，好的，谢谢
